export const CART_ACTION_TYPES = {
    TOGGLE_CART_OPEN: 'TOGGLE_CART_OPEN',
    SET_CART_ITEMS: 'SET_CART_ITEMS',
    UPDATE_TOTAL: 'UPDATE_TOTAL',
    UPDATE_TOTAL_QUANTITY: 'UPDATE_TOTAL_QUANTITY'
}